outputSource: test

kafka:
  bootstrapServer: kafka:9092
  groupID: abc1234
  topicConfigs:
    - db: customers_mongo
      tableName: customers
      schema: public
      topic: "dbserver1.inventory.customers"
      cdcFormat: debezium.mongodb
      # Turn this on if you plan to use JSON converter (see connect-distributed.properties)
      cdcKeyFormat: org.apache.kafka.connect.json.JsonConverter

snowflake:
  account: 123
  username: foo
  password: bar
  warehouse: dwh
  region: us-east-2.aws

telemetry:
  metrics:
    provider: datadog
    settings:
      tags:
       - env:production
      namespace: "transfer."
      addr: "127.0.0.1:8125"
