version: '3.9'
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:2.0
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: quay.io/debezium/kafka:2.0
    ports:
      - 9092:9092
      - 29092:29092
    links:
      - zookeeper
    environment:
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      ZOOKEEPER_CONNECT: zookeeper:2181
  mysql:
    image: quay.io/debezium/example-mysql:2.0
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
  debezium-server:
    image: quay.io/debezium/server:2.0
    container_name: debezium-server
    command: sh -c "sleep 15 && /debezium/run.sh"
    links:
      - kafka
      - mysql
    ports:
      - 8080:8080
    volumes:
      - ./application.properties:/debezium/conf/application.properties
    depends_on:
      - kafka
      - mysql
  transfer:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - kafka
      - mysql
